Ramscanner: ramscanner_common.h File Reference
ramscanner_common.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <glib.h>
#include "ramscanner_literals.h"
Data Structures
struct sizestats
struct vmastats
struct options
struct pagesummarydata
struct pagedetaildata
Functions
void * newkey (uint64_t key)
void destroyval (void *val)
void cleanup_and_exit (int signal)
static pid_t try_to_read_PID (const char *arg)
static void add_pid_to_array (pid_t pid, pid_t **pids, uint16_t *pidcount)
static FILE * open_arg (const char *arg)
void handle_args (int argc, char *argv[], options *opt)
void set_signals ()
void stop_PIDs (const pid_t *pids, uint16_t count)
Variables
pid_t * PIDs
uint16_t PIDcount
Function Documentation
static void add_pid_to_array (pid_t pid, pid_t ** pids, uint16_t * pidcount) [static]
void cleanup_and_exit (int signal)
Signal handler for abnormal termination. Tries its best to restart its stopped processes, but cannot guarantee total signal safety.
Definition at line 39 of file ramscanner_common.c.
References PIDcount, and PIDs.
Referenced by inspect_processes(), lookup_maps_with_PID(), lookup_pagemap_with_addresses(), lookup_smaps(), main(), make_another_vmst_in_opt(), set_signals(), stop_PIDs(), and use_pfn().
{
        int i = 0;
        for (i=0; i< PIDcount; i++)
                kill(PIDs[i], SIGCONT); /* Clears the queue of STOP signals. */
        if (signal != EXIT_SUCCESS && signal != EXIT_FAILURE)
                _exit(EXIT_FAILURE);
        else
                _exit(signal);
}
void destroyval (void * val)
A function to clear memory, passed to each GHashTable constructor so it knows how to destroy its data when the GHashTable's destructor is called. It is used for both key and value of the GHashTable.
Definition at line 29 of file ramscanner_common.c.
Referenced by main().
{
        free(val);
}
void handle_args (int argc, char * argv[], options * opt)
Parses the arguments given to the program. It ignores invalid arguments instead of failing. FILE pointers and PID arrays are set in the functions called, so are passed as pointers to pointers.
Definition at line 126 of file ramscanner_common.c.
References add_pid_to_array(), options::compactdetail, options::compactdetailfile, options::detail, options::detailfile, open_arg(), options::pidcount, options::pids, options::summary, options::summaryfile, and try_to_read_PID().
Referenced by main().
{
        char *optstr = "-s::d::D::";
        int o;
        pid_t pid;
        while ((o = getopt(argc, argv, optstr)) != -1) {
                switch(o) {
                case 1:
                        pid = try_to_read_PID(argv[optind - 1]);
                        if (pid != 0)
                                add_pid_to_array(pid, &(opt->pids),
                                                 &(opt->pidcount));
                        else
                                fprintf(stderr, "Warning: Received unexpected "
                                        "argument: %s. Ignoring.\n",
                                        argv[optind - 1]);
                        break;
                case 's':
                        opt->summary = 1;
                        if(optarg)
                                opt->summaryfile = open_arg(optarg);
                        else
                                opt->summaryfile = stdout;
                        break;
                case 'd':
                        opt->compactdetail = 1;
                        if(optarg)
                                opt->compactdetailfile = open_arg(optarg);
                        else
                                opt->compactdetailfile = stdout;
                        break;
                case 'D':
                        opt->detail = 1;
                        if(optarg)
                                opt->detailfile = open_arg(optarg);
                        else
                                opt->detailfile = stdout;
                        break;
                default:
                        printf("Received an unexpected option\n");
                }
        }
}
void* newkey (uint64_t key)
Boxes allocating dynamic memory and setting it to a value to a single function for easy insertion into a GHashTable.
Definition at line 16 of file ramscanner_common.c.
Referenced by lookup_pagemap_with_addresses(), and use_pfn().
{
        uint64_t *temp = malloc(sizeof(*temp));
        *temp = key;
        return temp;
}
static FILE* open_arg (const char * arg) [static]
void set_signals ()
Sets the signal handlers for this process to cleanup_and_exit().
Definition at line 174 of file ramscanner_common.c.
References cleanup_and_exit().
Referenced by main().
{
        struct sigaction sa;
                sa.sa_handler = cleanup_and_exit;
        if (sigaction(SIGTERM, &sa, NULL) == -1) {
                fprintf(stderr, "Error: Failed to set handler"
                        " to SIGTERM.");
                exit(EXIT_FAILURE);
        }
        if (sigaction(SIGINT, &sa, NULL) == -1) {
                fprintf(stderr, "Error: Failed to set handler"
                        " to SIGINT.");
                exit(EXIT_FAILURE);
        }
        if (sigaction(SIGSEGV, &sa, NULL) == -1) {
                fprintf(stderr, "Error: Failed to set handler"
                        " to SIGSEGV.");
                exit(EXIT_FAILURE);
        }
}
void stop_PIDs (const pid_t * pids, uint16_t count)
Stops the processes specified in pids, so they can be inspected without giving inconsistent results.
Definition at line 200 of file ramscanner_common.c.
References cleanup_and_exit().
Referenced by main().
{
        int i;
        for (i = 0; i < count; i++) {
                int ret;
                errno = 0;
                ret = kill(pids[i], SIGSTOP);/* SIGSTOP overrides signal
                                              * handling, consider SIGSTP.
                                              */
                if (ret == -1) {
                        perror("Error stopping PID");
                        cleanup_and_exit(EXIT_FAILURE);
                }
        }
}
static pid_t try_to_read_PID (const char * arg) [static]
Variable Documentation
uint16_t PIDcount
Definition at line 9 of file ramscanner_common.c.
Referenced by cleanup_and_exit(), and main().
pid_t* PIDs
Definition at line 8 of file ramscanner_common.c.
Referenced by cleanup_and_exit(), and main().