Ramscanner: ramscanner_display.h File Reference
ramscanner_display.h File Reference
#include "ramscanner_common.h"
Functions
void write_summary (const sizestats *stats, FILE *summary)
static void print_detail_format (FILE *file)
static void print_page_detail_data (pagedetaildata *page, FILE *file, vmastats *vmst)
static void write_compact_detail_page (void *key, void *val, void *userdata)
static void write_detail_page (void *key, void *val, void *userdata)
void write_any_detail (options *opt)
Function Documentation
static void print_detail_format (FILE * file) [static]
static void print_page_detail_data (pagedetaildata * page, FILE * file, vmastats * vmst) [static]
void write_any_detail (options * opt)
This function is called if either opt->compactdetail or opt->detail are set to true in opt. It prints the information stored within the GHashTable detailpages to the files specified by opt.
Definition at line 139 of file ramscanner_display.c.
References options::compactdetail, options::compactdetailfile, options::detail, options::detailfile, options::detailpages, print_detail_format(), write_compact_detail_page(), and write_detail_page().
Referenced by main().
{
        if (opt->compactdetail) {
                print_detail_format(opt->compactdetailfile);
                g_hash_table_foreach(opt->detailpages,
                                     &write_compact_detail_page, opt);
        }
        if (opt->detail) {
                print_detail_format(opt->detailfile);
                g_hash_table_foreach(opt->detailpages, &write_detail_page, opt);
        }
}
static void write_compact_detail_page (void * key, void * val, void * userdata) [static]
static void write_detail_page (void * key, void * val, void * userdata) [static]
void write_summary (const sizestats * stats, FILE * summary)
Write the summary data into the file specified as "summary".
Definition at line 10 of file ramscanner_display.c.
References sizestats::anon, DELIMITER, sizestats::gss, sizestats::locked, sizestats::pss, sizestats::refd, sizestats::rss, sizestats::sss, SUMMARY_ANON, SUMMARY_GSS, SUMMARY_LOCKED, SUMMARY_PSS, SUMMARY_REFD, SUMMARY_RSS, SUMMARY_SSS, SUMMARY_SWAP, SUMMARY_USS, SUMMARY_VSS, sizestats::swap, sizestats::uss, and sizestats::vss.
Referenced by main().
{
        fprintf(summary,"Type" DELIMITER "         Size(kB)\n");
        fprintf(summary,SUMMARY_VSS    DELIMITER "          %8u\n",stats->vss);
        fprintf(summary,SUMMARY_RSS    DELIMITER "          %8u\n",stats->rss);
        fprintf(summary,SUMMARY_PSS    DELIMITER "          %8u\n",stats->pss);
        fprintf(summary,SUMMARY_USS    DELIMITER "          %8u\n",stats->uss);
        fprintf(summary,SUMMARY_SSS    DELIMITER "          %8u\n",stats->sss);
        fprintf(summary,SUMMARY_GSS    DELIMITER "          %8u\n",stats->gss);
        fprintf(summary,SUMMARY_REFD   DELIMITER "   %8u\n",stats->refd);
        fprintf(summary,SUMMARY_SWAP   DELIMITER "         %8u\n",stats->swap);
        fprintf(summary,SUMMARY_ANON   DELIMITER "    %8u\n",stats->anon);
        fprintf(summary,SUMMARY_LOCKED DELIMITER "       %8u\n",stats->locked);
}