Ramscanner: ramscanner_display.c File Reference
ramscanner_display.c File Reference
#include <stdio.h>
#include <unistd.h>
#include "ramscanner_display.h"
Functions
void write_summary (const sizestats *stats, FILE *summary)
static void print_detail_format (FILE *file)
static void print_page_detail_data (pagedetaildata *page, FILE *file, vmastats *vmst)
static void write_compact_detail_page (void *key, void *val, void *userdata)
static void write_detail_page (void *key, void *val, void *userdata)
void write_any_detail (options *opt)
Function Documentation
static void print_detail_format (FILE * file) [static]
Write the head of the details in a detail file. Valid for compact detail and detail.
Definition at line 31 of file ramscanner_display.c.
References DELIMITER, DETAIL_ADDRENDTITLE, DETAIL_ADDRSTARTTITLE, DETAIL_ANONTITLE, DETAIL_DIRTYTITLE, DETAIL_KSMTITLE, DETAIL_LOCKEDTITLE, DETAIL_MAPPEDTITLE, DETAIL_PATHTITLE, DETAIL_PERMTITLE, DETAIL_PRESENTTITLE, DETAIL_REFDTITLE, DETAIL_SIZETITLE, DETAIL_SWAPBACKEDTITLE, DETAIL_SWAPCACHETITLE, and DETAIL_SWAPTITLE.
Referenced by write_any_detail().
{
        fprintf(file,            DETAIL_ADDRSTARTTITLE  DELIMITER
                                 DETAIL_ADDRENDTITLE    DELIMITER
                                 DETAIL_PERMTITLE       DELIMITER
                                 DETAIL_PATHTITLE       DELIMITER
                                 DETAIL_PRESENTTITLE    DELIMITER
                                 DETAIL_SIZETITLE       DELIMITER
                                 DETAIL_SWAPTITLE       DELIMITER
                                 DETAIL_MAPPEDTITLE     DELIMITER
                                 DETAIL_LOCKEDTITLE     DELIMITER
                                 DETAIL_REFDTITLE       DELIMITER
                                 DETAIL_DIRTYTITLE      DELIMITER
                                 DETAIL_ANONTITLE       DELIMITER
                                 DETAIL_SWAPCACHETITLE  DELIMITER
                                 DETAIL_SWAPBACKEDTITLE DELIMITER
                                 DETAIL_KSMTITLE        "\n");
}
static void print_page_detail_data (pagedetaildata * page, FILE * file, vmastats * vmst) [static]
Write the details data taken from the pagedetaildata struct into the file provided, taking some additional information from the vmastats.
Definition at line 55 of file ramscanner_display.c.
References pagedetaildata::anonymous, DELIMITER, DETAIL_NOANON, DETAIL_NODIRTY, DETAIL_NOKSM, DETAIL_NOLOCKED, DETAIL_NOPRESENT, DETAIL_NOREFD, DETAIL_NOSWAP, DETAIL_NOSWAPBACKED, DETAIL_NOSWAPCACHE, DETAIL_YESANON, DETAIL_YESDIRTY, DETAIL_YESKSM, DETAIL_YESLOCKED, DETAIL_YESPRESENT, DETAIL_YESREFD, DETAIL_YESSWAP, DETAIL_YESSWAPBACKED, DETAIL_YESSWAPCACHE, pagedetaildata::dirty, pagedetaildata::ksm, pagedetaildata::locked, pagedetaildata::pageshift, vmastats::path, vmastats::permissions, pagedetaildata::present, pagedetaildata::referenced, pagedetaildata::swap, pagedetaildata::swapbacked, pagedetaildata::swapcache, and pagedetaildata::timesmapped.
Referenced by write_compact_detail_page(), and write_detail_page().
{
        fprintf(file, "%5s"DELIMITER,  vmst->permissions);
        fprintf(file, "%s" DELIMITER,  vmst->path);
        fprintf(file, "%s" DELIMITER, (page->present ?
                                       DETAIL_YESPRESENT :
                                       DETAIL_NOPRESENT ));
        fprintf(file, "%d" DELIMITER, (1 << page->pageshift));
        fprintf(file, "%s" DELIMITER, (page->swap ?
                                       DETAIL_YESSWAP :
                                       DETAIL_NOSWAP ));
        fprintf(file, "%d"DELIMITER, page->timesmapped);
        fprintf(file, "%s"DELIMITER, (page->locked ?
                                      DETAIL_YESLOCKED :
                                      DETAIL_NOLOCKED ));
        fprintf(file, "%s"DELIMITER, (page->referenced ?
                                      DETAIL_YESREFD :
                                      DETAIL_NOREFD ));
        fprintf(file, "%s"DELIMITER, (page->dirty ?
                                      DETAIL_YESDIRTY :
                                      DETAIL_NODIRTY ));
        fprintf(file, "%s"DELIMITER, (page->anonymous ?
                                      DETAIL_YESANON :
                                      DETAIL_NOANON ));
        fprintf(file, "%s"DELIMITER, (page->swapcache ?
                                      DETAIL_YESSWAPCACHE :
                                      DETAIL_NOSWAPCACHE ));
        fprintf(file, "%s"DELIMITER, (page->swapbacked ?
                                      DETAIL_YESSWAPBACKED :
                                      DETAIL_NOSWAPBACKED ));
        fprintf(file, "%s"DELIMITER, (page->ksm ?
                                      DETAIL_YESKSM :
                                      DETAIL_NOKSM ));
}
void write_any_detail (options * opt)
This function is called if either opt->compactdetail or opt->detail are set to true in opt. It prints the information stored within the GHashTable detailpages to the files specified by opt.
Definition at line 139 of file ramscanner_display.c.
References options::compactdetail, options::compactdetailfile, options::detail, options::detailfile, options::detailpages, print_detail_format(), write_compact_detail_page(), and write_detail_page().
Referenced by main().
{
        if (opt->compactdetail) {
                print_detail_format(opt->compactdetailfile);
                g_hash_table_foreach(opt->detailpages,
                                     &write_compact_detail_page, opt);
        }
        if (opt->detail) {
                print_detail_format(opt->detailfile);
                g_hash_table_foreach(opt->detailpages, &write_detail_page, opt);
        }
}
static void write_compact_detail_page (void * key, void * val, void * userdata) [static]
Function passed into a g_hash_table_foreach(). Takes the details from the page and prints the information with the help of the print_page_detail_data() function.
Definition at line 99 of file ramscanner_display.c.
References pagedetaildata::addrend, pagedetaildata::addrstart, options::compactdetailfile, DELIMITER, print_page_detail_data(), pagedetaildata::vmaindex, and options::vmas.
Referenced by write_any_detail().
{
        options *opt = userdata;
        pagedetaildata *page = val;
        vmastats *currentvmst = &(opt->vmas[page->vmaindex]);
        uint32_t pagecount = (page->addrend - page->addrstart) / getpagesize();
        fprintf(opt->compactdetailfile, "%08x" DELIMITER, page->addrstart);
        fprintf(opt->compactdetailfile, "%08x" DELIMITER, page->addrend);
        print_page_detail_data(page, opt->compactdetailfile, currentvmst);
        fprintf(opt->compactdetailfile, "%d" DELIMITER" identical pages\n",
                pagecount);
}
static void write_detail_page (void * key, void * val, void * userdata) [static]
Like write_compact_detail_page(), retrieves information from the page. This function expands the information into one line per page mapped.
Definition at line 117 of file ramscanner_display.c.
References pagedetaildata::addrstart, DELIMITER, options::detailfile, print_page_detail_data(), pagedetaildata::vmaindex, and options::vmas.
Referenced by write_any_detail().
{
        options *opt = userdata;
        pagedetaildata *page = val;
        vmastats *currentvmst = &(opt->vmas[page->vmaindex]);
        uint32_t i;
        size_t size = getpagesize();
        for (i = page->addrstart; i < page->addrend; i += size) {
                fprintf(opt->detailfile, "%x" DELIMITER, i);
                fprintf(opt->detailfile, "%x" DELIMITER, (i + size));
                print_page_detail_data(page, opt->detailfile, currentvmst);
                fprintf(opt->detailfile, "\n");
        }
}
void write_summary (const sizestats * stats, FILE * summary)
Write the summary data into the file specified as "summary".
Definition at line 10 of file ramscanner_display.c.
References sizestats::anon, DELIMITER, sizestats::gss, sizestats::locked, sizestats::pss, sizestats::refd, sizestats::rss, sizestats::sss, SUMMARY_ANON, SUMMARY_GSS, SUMMARY_LOCKED, SUMMARY_PSS, SUMMARY_REFD, SUMMARY_RSS, SUMMARY_SSS, SUMMARY_SWAP, SUMMARY_USS, SUMMARY_VSS, sizestats::swap, sizestats::uss, and sizestats::vss.
Referenced by main().
{
        fprintf(summary,"Type" DELIMITER "         Size(kB)\n");
        fprintf(summary,SUMMARY_VSS    DELIMITER "          %8u\n",stats->vss);
        fprintf(summary,SUMMARY_RSS    DELIMITER "          %8u\n",stats->rss);
        fprintf(summary,SUMMARY_PSS    DELIMITER "          %8u\n",stats->pss);
        fprintf(summary,SUMMARY_USS    DELIMITER "          %8u\n",stats->uss);
        fprintf(summary,SUMMARY_SSS    DELIMITER "          %8u\n",stats->sss);
        fprintf(summary,SUMMARY_GSS    DELIMITER "          %8u\n",stats->gss);
        fprintf(summary,SUMMARY_REFD   DELIMITER "   %8u\n",stats->refd);
        fprintf(summary,SUMMARY_SWAP   DELIMITER "         %8u\n",stats->swap);
        fprintf(summary,SUMMARY_ANON   DELIMITER "    %8u\n",stats->anon);
        fprintf(summary,SUMMARY_LOCKED DELIMITER "       %8u\n",stats->locked);
}